version: "3.8"
secrets:
  clientId:
    environment: "AZURE_CLIENT_ID"
  clientSecret:
    environment: "AZURE_CLIENT_SECRET"
  tenantId:
    environment: "AZURE_TENANT_ID"
services:
  portal:
    image: ghcr.io/compliance-framework/portal:latest
    ports:
      - "8081:8081"
    depends_on:
      - configuration-service
  configuration-service:
    image: ghcr.io/compliance-framework/configuration-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - nats
    environment:
      - NATS_URI=nats://nats:4222
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  plugin-registry:
    image: ghcr.io/compliance-framework/plugin-registry:latest
    ports:
      - "3000:3000"
  nats:
    image: nats:latest
    volumes:
      - ./nats-server.conf:/nats-server.conf
    ports:
      - "4222:4222"
  assessment-runtime:
    image: ghcr.io/compliance-framework/assessment-runtime:latest
    depends_on:
      - plugin-registry
    secrets:
      - clientId
      - clientSecret
      - tenantId
