version: '3.8'
secrets:
  clientId:
    environment: "AZURE_CLIENT_ID"
  clientSecret:
    environment: "AZURE_CLIENT_SECRET"
  tenantId:
    environment: "AZURE_TENANT_ID"
services:
  portal:
    build: 
      context: ${PWD}/portal
      dockerfile: ${PWD}/portal/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - configuration-service
    environment:
      - VITE_CONFIGURATION_SERVICE_URL="http://infrastructure-configuration-service-1:8080/api"
      #- VITE_CONFIGURATION_SERVICE_URL="http://localhost:8080/api"
  configuration-service:
    build: 
      context: ${PWD}/configuration-service
      dockerfile: ${PWD}/configuration-service/Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - nats
    environment:
      - NATS_URI=nats://nats:4222
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  plugin-registry:
    build:
      context: ${PWD}/assessment-runtime
      dockerfile: test/registry/Dockerfile
    ports:
      - "3000:3000"
  nats:
    image: nats:latest
    volumes:
      - ${PWD}/assessment-runtime/test/config/messaging/nats-server.conf:/nats-server.conf
    ports:
      - "4222:4222"
  assessment-runtime:
    build:
      context: ${PWD}/assessment-runtime
      dockerfile: ${PWD}/assessment-runtime/test/runtime/Dockerfile
    depends_on:
      - plugin-registry
    secrets:
    - clientId
    - clientSecret
    - tenantId