version: "3.8"
secrets:
  clientId:
    environment: "AZURE_CLIENT_ID"
  clientSecret:
    environment: "AZURE_CLIENT_SECRET"
  tenantId:
    environment: "AZURE_TENANT_ID"
services:
  configuration-service:
    image: ghcr.io/compliance-framework/configuration-service:${CS_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - nats
    environment:
      - NATS_URI=nats://nats:4222
      - MONGO_URI=mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  plugin-registry:
    image: ghcr.io/compliance-framework/plugin-registry:${PR_TAG}
    ports:
      - "3001:80"
  nats:
    image: nats:latest
    volumes:
      - ./nats-server.conf:/nats-server.conf
    ports:
      - "4222:4222"
  assessment-runtime:
    image: ghcr.io/compliance-framework/assessment-runtime:${AR_TAG}
    depends_on:
      - plugin-registry
    secrets:
      - clientId
      - clientSecret
      - tenantId
